### ISSUE TITLE
[Feature] Try to find a way to login using account name and password

### ISSUE THREAD

**Issue by yt6983138** [yt6983138/PSLDiscordBot#1]
Try to find a way to login using account name and password, need future work on this, may need request grabbing. <br/>
Resources may be helpful:
1. https://github.com/leancloud/csharp-sdk
2. https://github.com/7aGiven/PhigrosLibrary
3. https://github.com/catrong/phi-plugin
4. https://github.com/leancloud/csharp-sdk/blob/master/Storage/Storage/Public/User/LCUser.cs
5. https://github.com/leancloud/csharp-sdk/blob/master/Common/Common/Http/LCHttpClient.cs#L111

**Comment by ghost** [comment]
是的，我认为这将是一个很棒的功能。 你有一个 SQL 数据库来存储用户的用户名和密码吗？ 以纯文本形式存储它们是非常不安全的。

**Comment by yt6983138** [comment]
> 是的，我认为这将是一个很棒的功能。 你有一个 SQL 数据库来存储用户的用户名和密码吗？ 以纯文本形式存储它们是非常不安全的。

actually i don't have a plan for that, because we don't save the password at all, we only stores token & user id. also i see that the user base may be larger in the future, but will it even over 50 users? that's a good question, also save in SQL database don't really add extra security except encrypted, and the operation is slow

**Comment by yt6983138** [comment]
Added at https://github.com/yt6983138/PhigrosLibraryCSharp/commit/0e46b649905e79f2fe09a9ce562904d1ff852386 
will be merged into the bot later

**Comment by yt6983138** [comment]
> 是的，我认为这将是一个很棒的功能。 你有一个 SQL 数据库来存储用户的用户名和密码吗？ 以纯文本形式存储它们是非常不安全的。

ok coming back to this we have 471 users now lmao

also we r using sqlite now lol
