### ISSUE TITLE
Make bigger image

### ISSUE THREAD

**Issue by syesjohnny** [yt6983138/PSLDiscordBot#4]
It's too small🤏
Make image even bigger than your dicc

**Comment by yt6983138** [comment]
i should implement a custom format to do the jobs, anyways I'll be fixing the difficulty missing problem for you

**Comment by yt6983138** [comment]
ok i figured out that it was because i added an equal sign while comparing the length so yea hot fix will be available soon

now ill be working on bigger images

**Comment by yt6983138** [comment]
done in [a658b56](https://github.com/yt6983138/PSLDiscordBot/commit/a658b5665df7394f2dc2601fc0f3178a63a17401)
